// ============================================================================
// NNPC Gas Platform - Real Seed Data
// Based on actual NNPC reporting workbooks
// Source: NNPC_Frontend_Update_Spec_v2.md Section 5
// ============================================================================

import { Producer, Offtaker, Franchise } from "./types";

// ============================================================================
// PRODUCERS (Supply Sources) - Western Network
// From Weekly MOR reports
// ============================================================================

export const producersWestern: Producer[] = [
  {
    id: "prod-w-001",
    name: "CNL-Escravos",
    network: "Western Network",
    plantCapacity: 450,
    productionForecast: 445,
    averageDailyProduction: 442,
    excessShortfall: -3,
    contractualPressureRange: { min: 80, max: 85 },
    contractualPressureRangeStr: "80 - 85",
  },
  {
    id: "prod-w-002",
    name: "NEPL/NDW Utorogu",
    network: "Western Network",
    plantCapacity: 520,
    productionForecast: 510,
    averageDailyProduction: 505,
    excessShortfall: -5,
    contractualPressureRange: { min: 70, max: 80 },
    contractualPressureRangeStr: "70 - 80",
  },
  {
    id: "prod-w-003",
    name: "NEPL Oredo FST3 (OGPOOC)",
    network: "Western Network",
    plantCapacity: 420,
    productionForecast: 415,
    averageDailyProduction: 405,
    excessShortfall: -10,
    contractualPressureRange: { min: 55, max: 70 },
    contractualPressureRangeStr: "55 - 70",
    remarks: "Pressure below contractual range - investigate",
  },
  {
    id: "prod-w-004",
    name: "NEPL Oredo (IGHF)",
    network: "Western Network",
    plantCapacity: 280,
    productionForecast: 275,
    averageDailyProduction: 272,
    excessShortfall: -3,
    contractualPressureRange: { min: 60, max: 75 },
    contractualPressureRangeStr: "60 - 75",
  },
  {
    id: "prod-w-005",
    name: "Pan Ocean",
    network: "Western Network",
    plantCapacity: 180,
    productionForecast: 175,
    averageDailyProduction: 178,
    excessShortfall: 3,
    contractualPressureRange: { min: 65, max: 78 },
    contractualPressureRangeStr: "65 - 78",
  },
  {
    id: "prod-w-006",
    name: "Seplat Oben",
    network: "Western Network",
    plantCapacity: 310,
    productionForecast: 305,
    averageDailyProduction: 308,
    excessShortfall: 3,
    contractualPressureRange: { min: 68, max: 80 },
    contractualPressureRangeStr: "68 - 80",
  },
  {
    id: "prod-w-007",
    name: "SPDC Tunu/FYIP/Otumara",
    network: "Western Network",
    plantCapacity: 580,
    productionForecast: 570,
    averageDailyProduction: 565,
    excessShortfall: -5,
    contractualPressureRange: { min: 72, max: 85 },
    contractualPressureRangeStr: "72 - 85",
  },
  {
    id: "prod-w-008",
    name: "NEPL/Neconde Odidi",
    network: "Western Network",
    plantCapacity: 220,
    productionForecast: 215,
    averageDailyProduction: 218,
    excessShortfall: 3,
    contractualPressureRange: { min: 62, max: 75 },
    contractualPressureRangeStr: "62 - 75",
  },
  {
    id: "prod-w-009",
    name: "AHL",
    network: "Western Network",
    plantCapacity: 95,
    productionForecast: 92,
    averageDailyProduction: 90,
    excessShortfall: -2,
    contractualPressureRange: { min: 55, max: 68 },
    contractualPressureRangeStr: "55 - 68",
  },
  {
    id: "prod-w-010",
    name: "Platform Petroleum",
    network: "Western Network",
    plantCapacity: 125,
    productionForecast: 120,
    averageDailyProduction: 122,
    excessShortfall: 2,
    contractualPressureRange: { min: 58, max: 70 },
    contractualPressureRangeStr: "58 - 70",
  },
  {
    id: "prod-w-011",
    name: "Xenergi",
    network: "Western Network",
    plantCapacity: 85,
    productionForecast: 82,
    averageDailyProduction: 83,
    excessShortfall: 1,
    contractualPressureRange: { min: 54, max: 66 },
    contractualPressureRangeStr: "54 - 66",
  },
  {
    id: "prod-w-012",
    name: "NEPL Ughelli",
    network: "Western Network",
    plantCapacity: 380,
    productionForecast: 375,
    averageDailyProduction: 372,
    excessShortfall: -3,
    contractualPressureRange: { min: 66, max: 78 },
    contractualPressureRangeStr: "66 - 78",
  },
  {
    id: "prod-w-013",
    name: "Chorus Energy",
    network: "Western Network",
    plantCapacity: 105,
    productionForecast: 102,
    averageDailyProduction: 104,
    excessShortfall: 2,
    contractualPressureRange: { min: 56, max: 68 },
    contractualPressureRangeStr: "56 - 68",
  },
];

// ============================================================================
// FRANCHISES / UJVs - Real names from NGML reports
// ============================================================================

export const franchises: Franchise[] = [
  {
    id: "franchise-001",
    name: "NGML-NIPCO UJV",
    type: "UJV",
    gdz: "REGIONAL GAS DISTRIBUTION LAGOS",
    memberOfftakerIds: [
      "off-lpl-rccg",
      "off-olam",
      "off-breeze",
      "off-nestle",
      "off-aiml",
    ],
  },
  {
    id: "franchise-002",
    name: "TRANSIT GAS FRANCHISE",
    type: "Franchise",
    gdz: "REGIONAL GAS DISTRIBUTION LAGOS",
    memberOfftakerIds: [
      "off-apple-pears",
      "off-wasil",
      "off-uraga",
      "off-emzor",
      "off-rite-foods",
      "off-lad-group",
      "off-agricon",
    ],
  },
  {
    id: "franchise-003",
    name: "ENTEC GAS FRANCHISE",
    type: "Franchise",
    gdz: "REGIONAL GAS DISTRIBUTION NORTH",
    memberOfftakerIds: [
      "off-nixin",
      "off-flex-films",
      "off-fan-renewable",
      "off-tiget",
    ],
  },
  {
    id: "franchise-004",
    name: "GREEN FUELS UJV",
    type: "UJV",
    gdz: "REGIONAL GAS DISTRIBUTION DELTA",
    memberOfftakerIds: ["off-sigma", "off-dahua"],
  },
];

// ============================================================================
// OFFTAKERS - Real NNPC Customer Names
// ============================================================================

// Western / Lagos Power Customers
export const offtakersPowerWestern: Offtaker[] = [
  {
    id: "off-transcorp-ughelli",
    name: "Transcorp Ughelli",
    corridor: "Western",
    sector: "Power",
    productType: "Lean gas",
    deliveryPointId: "dp-transcorp-ughelli",
    designCapacity: 220,
    contractualDemand: 215,
    firmAndEffective: 200,
    firmNotEffective: 0,
    interruptible: 15,
    estimatedDemand: 210,
    customerClass: "Sales",
    aliases: ["Transcorp Ughelli", "Transcorp Power"],
  },
  {
    id: "off-azura",
    name: "Azura Power West Africa",
    corridor: "Western",
    sector: "Power",
    productType: "Lean gas",
    deliveryPointId: "dp-azura",
    designCapacity: 300,
    contractualDemand: 295,
    firmAndEffective: 280,
    firmNotEffective: 0,
    interruptible: 15,
    estimatedDemand: 290,
    customerClass: "Sales",
    aliases: ["Azura Power", "Azura Power West Africa"],
  },
  {
    id: "off-ndphc-olorunsogo",
    name: "NDPHC NIPP Olorunsogo",
    corridor: "Western",
    sector: "Power",
    productType: "Lean gas",
    deliveryPointId: "dp-ndphc-olorunsogo",
    designCapacity: 180,
    contractualDemand: 175,
    firmAndEffective: 165,
    firmNotEffective: 0,
    interruptible: 10,
    estimatedDemand: 170,
    customerClass: "Sales",
    aliases: ["NDPHC Olorunsogo", "NIPP Olorunsogo"],
  },
  {
    id: "off-nipp-ihovbor",
    name: "NIPP Ihovbor",
    corridor: "Western",
    sector: "Power",
    productType: "Lean gas",
    deliveryPointId: "dp-nipp-ihovbor",
    designCapacity: 140,
    contractualDemand: 135,
    firmAndEffective: 130,
    firmNotEffective: 0,
    interruptible: 5,
    estimatedDemand: 132,
    customerClass: "Sales",
  },
  {
    id: "off-nipp-omotosho",
    name: "NIPP Omotosho",
    corridor: "Western",
    sector: "Power",
    productType: "Lean gas",
    deliveryPointId: "dp-nipp-omotosho",
    designCapacity: 160,
    contractualDemand: 155,
    firmAndEffective: 150,
    firmNotEffective: 0,
    interruptible: 5,
    estimatedDemand: 152,
    customerClass: "Sales",
  },
  {
    id: "off-nipp-geregu",
    name: "NIPP Geregu",
    corridor: "Northern",
    sector: "Power",
    productType: "Lean gas",
    deliveryPointId: "dp-nipp-geregu",
    designCapacity: 145,
    contractualDemand: 140,
    firmAndEffective: 135,
    firmNotEffective: 0,
    interruptible: 5,
    estimatedDemand: 138,
    customerClass: "Sales",
  },
  {
    id: "off-nipp-sapele",
    name: "NIPP Sapele",
    corridor: "Western",
    sector: "Power",
    productType: "Lean gas",
    deliveryPointId: "dp-nipp-sapele",
    designCapacity: 125,
    contractualDemand: 120,
    firmAndEffective: 115,
    firmNotEffective: 0,
    interruptible: 5,
    estimatedDemand: 118,
    customerClass: "Sales",
  },
  {
    id: "off-egbin",
    name: "Egbin",
    corridor: "Lagos",
    sector: "Power",
    productType: "Lean gas",
    deliveryPointId: "dp-egbin",
    designCapacity: 240,
    contractualDemand: 235,
    firmAndEffective: 220,
    firmNotEffective: 0,
    interruptible: 15,
    estimatedDemand: 230,
    customerClass: "Sales",
    aliases: ["Egbin Power Station", "Egbin"],
  },
];

// Industrial / Commercial Customers (Western)
export const offtakersIndustrialWestern: Offtaker[] = [
  {
    id: "off-gaslink",
    name: "GASLINK",
    corridor: "Western",
    sector: "Other industry",
    productType: "Lean gas",
    deliveryPointId: "dp-gaslink",
    designCapacity: 230,
    contractualDemand: 228,
    firmAndEffective: 215,
    firmNotEffective: 0,
    interruptible: 13,
    estimatedDemand: 225,
    customerClass: "Sales",
    aliases: ["GASLINK", "GAS LINK"],
  },
  {
    id: "off-falcon",
    name: "Falcon Petroleum",
    corridor: "Western",
    sector: "Petrochemical",
    productType: "Lean gas",
    deliveryPointId: "dp-falcon",
    designCapacity: 45,
    contractualDemand: 43,
    firmAndEffective: 40,
    firmNotEffective: 0,
    interruptible: 3,
    estimatedDemand: 42,
    customerClass: "Sales",
    aliases: ["Falcon Petroleum", "Falcon"],
  },
  {
    id: "off-wapco-sagamu",
    name: "WAPCO Sagamu",
    corridor: "Western",
    sector: "Cement",
    productType: "Lean gas",
    deliveryPointId: "dp-wapco-sagamu",
    designCapacity: 20,
    contractualDemand: 18,
    firmAndEffective: 17,
    firmNotEffective: 0,
    interruptible: 1,
    estimatedDemand: 17.5,
    customerClass: "Sales",
    aliases: ["WAPCO Sagamu", "WAPCO SHAG"],
  },
  {
    id: "off-wapco-ewekoro",
    name: "WAPCO Ewekoro",
    corridor: "Western",
    sector: "Cement",
    productType: "Lean gas",
    deliveryPointId: "dp-wapco-ewekoro",
    designCapacity: 118,
    contractualDemand: 115,
    firmAndEffective: 110,
    firmNotEffective: 0,
    interruptible: 5,
    estimatedDemand: 113,
    customerClass: "Sales",
    aliases: ["WAPCO Ewekoro", "WAPCO EWEK"],
  },
  {
    id: "off-ibeshe",
    name: "Ibeshe Cement",
    corridor: "Western",
    sector: "Cement",
    productType: "Lean gas",
    deliveryPointId: "dp-ibeshe",
    designCapacity: 285,
    contractualDemand: 280,
    firmAndEffective: 270,
    firmNotEffective: 0,
    interruptible: 10,
    estimatedDemand: 278,
    customerClass: "Sales",
  },
  {
    id: "off-obajana",
    name: "Obajana Cement",
    corridor: "Western",
    sector: "Cement",
    productType: "Lean gas",
    deliveryPointId: "dp-obajana",
    designCapacity: 55,
    contractualDemand: 50,
    firmAndEffective: 50,
    firmNotEffective: 0,
    interruptible: 0,
    estimatedDemand: 50,
    customerClass: "Sales",
    aliases: ["Obajana Cement", "Dangote Obajana"],
  },
  {
    id: "off-bua",
    name: "BUA Cement",
    corridor: "Western",
    sector: "Cement",
    productType: "Lean gas",
    deliveryPointId: "dp-bua",
    designCapacity: 35,
    contractualDemand: 33,
    firmAndEffective: 33,
    firmNotEffective: 0,
    interruptible: 0,
    estimatedDemand: 33,
    customerClass: "Sales",
    aliases: ["BUA Cement", "BUA"],
  },
  {
    id: "off-dfl",
    name: "DFL (Dangote Fertiliser)",
    corridor: "Western",
    sector: "Fertiliser",
    productType: "Lean gas",
    deliveryPointId: "dp-dfl",
    designCapacity: 200,
    contractualDemand: 195,
    firmAndEffective: 185,
    firmNotEffective: 0,
    interruptible: 10,
    estimatedDemand: 192,
    customerClass: "Sales",
    aliases: ["DFL", "Dangote Fertiliser"],
  },
  {
    id: "off-sng",
    name: "SNG",
    corridor: "Western",
    sector: "LDC / distributor",
    productType: "Lean gas",
    deliveryPointId: "dp-sng",
    designCapacity: 12,
    contractualDemand: 10,
    firmAndEffective: 10,
    firmNotEffective: 0,
    interruptible: 0,
    estimatedDemand: 10,
    customerClass: "Sales",
    gdz: "REGIONAL GAS DISTRIBUTION LAGOS",
    aliases: ["SNG", "SNG Aba", "Aba-SNG"], // May be different stations - needs confirmation
  },
];

// NGML Franchise Customers (Lagos)
export const offtakersFranchiseLagos: Offtaker[] = [
  // NGML-NIPCO UJV
  {
    id: "off-lpl-rccg",
    name: "LPL G/PWR (RCCG)",
    corridor: "Lagos",
    sector: "Power",
    productType: "Lean gas",
    deliveryPointId: "dp-lpl-rccg",
    designCapacity: 12,
    contractualDemand: 10,
    firmAndEffective: 9,
    firmNotEffective: 0,
    interruptible: 1,
    estimatedDemand: 9.5,
    customerClass: "Sales",
    franchiseId: "franchise-001",
    gdz: "REGIONAL GAS DISTRIBUTION LAGOS",
  },
  {
    id: "off-olam",
    name: "OLAM",
    corridor: "Lagos",
    sector: "Other industry",
    productType: "Lean gas",
    deliveryPointId: "dp-olam",
    designCapacity: 8,
    contractualDemand: 7,
    firmAndEffective: 6.5,
    firmNotEffective: 0,
    interruptible: 0.5,
    estimatedDemand: 6.8,
    customerClass: "Sales",
    franchiseId: "franchise-001",
    gdz: "REGIONAL GAS DISTRIBUTION LAGOS",
  },
  {
    id: "off-breeze",
    name: "BREEZE IND LTD",
    corridor: "Lagos",
    sector: "Other industry",
    productType: "Lean gas",
    deliveryPointId: "dp-breeze",
    designCapacity: 5,
    contractualDemand: 4,
    firmAndEffective: 3.8,
    firmNotEffective: 0,
    interruptible: 0.2,
    estimatedDemand: 3.9,
    customerClass: "Sales",
    franchiseId: "franchise-001",
    gdz: "REGIONAL GAS DISTRIBUTION LAGOS",
  },
  {
    id: "off-nestle",
    name: "NESTLE",
    corridor: "Lagos",
    sector: "Other industry",
    productType: "Lean gas",
    deliveryPointId: "dp-nestle",
    designCapacity: 15,
    contractualDemand: 14,
    firmAndEffective: 13,
    firmNotEffective: 0,
    interruptible: 1,
    estimatedDemand: 13.5,
    customerClass: "Sales",
    franchiseId: "franchise-001",
    gdz: "REGIONAL GAS DISTRIBUTION LAGOS",
  },
  {
    id: "off-aiml",
    name: "AIML",
    corridor: "Lagos",
    sector: "Other industry",
    productType: "Lean gas",
    deliveryPointId: "dp-aiml",
    designCapacity: 6,
    contractualDemand: 5,
    firmAndEffective: 4.5,
    firmNotEffective: 0,
    interruptible: 0.5,
    estimatedDemand: 4.8,
    customerClass: "Sales",
    franchiseId: "franchise-001",
    gdz: "REGIONAL GAS DISTRIBUTION LAGOS",
  },

  // TRANSIT GAS FRANCHISE
  {
    id: "off-apple-pears",
    name: "APPLE&PEARS",
    corridor: "Lagos",
    sector: "Other industry",
    productType: "Lean gas",
    deliveryPointId: "dp-apple-pears",
    designCapacity: 6,
    contractualDemand: 5,
    firmAndEffective: 4.5,
    firmNotEffective: 0,
    interruptible: 0.5,
    estimatedDemand: 4.8,
    customerClass: "Sales",
    franchiseId: "franchise-002",
    gdz: "REGIONAL GAS DISTRIBUTION LAGOS",
  },
  {
    id: "off-wasil",
    name: "WASIL",
    corridor: "Lagos",
    sector: "Other industry",
    productType: "Lean gas",
    deliveryPointId: "dp-wasil",
    designCapacity: 4,
    contractualDemand: 3,
    firmAndEffective: 2.8,
    firmNotEffective: 0,
    interruptible: 0.2,
    estimatedDemand: 2.9,
    customerClass: "Sales",
    franchiseId: "franchise-002",
    gdz: "REGIONAL GAS DISTRIBUTION LAGOS",
  },
  {
    id: "off-uraga",
    name: "URAGA POWER",
    corridor: "Lagos",
    sector: "Power",
    productType: "Lean gas",
    deliveryPointId: "dp-uraga",
    designCapacity: 20,
    contractualDemand: 18,
    firmAndEffective: 17,
    firmNotEffective: 0,
    interruptible: 1,
    estimatedDemand: 17.5,
    customerClass: "Sales",
    franchiseId: "franchise-002",
    gdz: "REGIONAL GAS DISTRIBUTION LAGOS",
  },
  {
    id: "off-emzor",
    name: "EMZOR",
    corridor: "Lagos",
    sector: "Other industry",
    productType: "Lean gas",
    deliveryPointId: "dp-emzor",
    designCapacity: 3,
    contractualDemand: 2.5,
    firmAndEffective: 2.3,
    firmNotEffective: 0,
    interruptible: 0.2,
    estimatedDemand: 2.4,
    customerClass: "Sales",
    franchiseId: "franchise-002",
    gdz: "REGIONAL GAS DISTRIBUTION LAGOS",
  },
  {
    id: "off-rite-foods",
    name: "RITE FOODS",
    corridor: "Lagos",
    sector: "Other industry",
    productType: "Lean gas",
    deliveryPointId: "dp-rite-foods",
    designCapacity: 7,
    contractualDemand: 6.5,
    firmAndEffective: 6,
    firmNotEffective: 0,
    interruptible: 0.5,
    estimatedDemand: 6.2,
    customerClass: "Sales",
    franchiseId: "franchise-002",
    gdz: "REGIONAL GAS DISTRIBUTION LAGOS",
  },
  {
    id: "off-lad-group",
    name: "LAD GROUP",
    corridor: "Lagos",
    sector: "Other industry",
    productType: "Lean gas",
    deliveryPointId: "dp-lad-group",
    designCapacity: 5,
    contractualDemand: 4.5,
    firmAndEffective: 4.2,
    firmNotEffective: 0,
    interruptible: 0.3,
    estimatedDemand: 4.3,
    customerClass: "Sales",
    franchiseId: "franchise-002",
    gdz: "REGIONAL GAS DISTRIBUTION LAGOS",
  },
  {
    id: "off-agricon",
    name: "AGRICON",
    corridor: "Lagos",
    sector: "Other industry",
    productType: "Lean gas",
    deliveryPointId: "dp-agricon",
    designCapacity: 4,
    contractualDemand: 3.5,
    firmAndEffective: 3.3,
    firmNotEffective: 0,
    interruptible: 0.2,
    estimatedDemand: 3.4,
    customerClass: "Sales",
    franchiseId: "franchise-002",
    gdz: "REGIONAL GAS DISTRIBUTION LAGOS",
  },
];

// Eastern Customers
export const offtakersEastern: Offtaker[] = [
  {
    id: "off-trans-afam",
    name: "Trans-Afam",
    corridor: "Eastern",
    sector: "Power",
    productType: "Lean gas",
    deliveryPointId: "dp-trans-afam",
    designCapacity: 190,
    contractualDemand: 185,
    firmAndEffective: 175,
    firmNotEffective: 0,
    interruptible: 10,
    estimatedDemand: 180,
    customerClass: "Sales",
  },
  {
    id: "off-notore",
    name: "Notore Chemicals",
    corridor: "Eastern",
    sector: "Fertiliser",
    productType: "Lean gas",
    deliveryPointId: "dp-notore",
    designCapacity: 38,
    contractualDemand: 35,
    firmAndEffective: 33,
    firmNotEffective: 0,
    interruptible: 2,
    estimatedDemand: 34,
    customerClass: "Sales",
    aliases: ["Notore Chemicals", "Notore Chemical Industries"],
  },
];

// Export all seed data
export const allProducers = [...producersWestern];
export const allOfftakers = [
  ...offtakersPowerWestern,
  ...offtakersIndustrialWestern,
  ...offtakersFranchiseLagos,
  ...offtakersEastern,
];
