// Upload/Export configurations for each report type

import { formatDateForCSV } from "./csv-utils";

export const REPORT_CONFIGS = {
  nominations: {
    templateType: "nominations" as const,
    identifierFields: ["gasDay", "offtaker"],
    requiredFields: ["Date", "Customer", "DCQ (MMscf/d)", "Nominated (MMscf/d)"],
    transformUploadData: (row: any, index: number) => ({
      id: `nom-upload-${Date.now()}-${index}`,
      gasDay: formatDateForCSV(row.Date || row.date),
      corridor: row.Corridor || row.corridor || "Eastern",
      offtaker: row.Customer || row.customer || row.offtaker,
      dcq: parseFloat(row["DCQ (MMscf/d)"] || row.dcq || 0),
      priorityLevel: "Normal",
      requestedBy: "System Upload",
      nominatedVolume: parseFloat(row["Nominated (MMscf/d)"] || row.nominated || 0),
      allocatedVolume: parseFloat(row["Allocated (MMscf/d)"] || row.allocated || row["Confirmed (MMscf/d)"] || row.confirmed || row["Nominated (MMscf/d)"] || 0),
      forecastSupply: parseFloat(row["Forecast Supply (MMscf/d)"] || row.forecastSupply || row["Nominated (MMscf/d)"] || 0),
      actualSupplied: parseFloat(row["Actual Supplied (MMscf/d)"] || row.actualSupplied || 0),
      received: parseFloat(row["Received (MMscf/d)"] || row.received || 0),
      offtaken: parseFloat(row["Offtaken (MMscf/d)"] || row.offtaken || 0),
      allocationVsDcq: 0,
    }),
    transformExportData: (record: any) => ({
      Date: record.gasDay,
      Customer: record.offtaker,
      Corridor: record.corridor,
      "DCQ (MMscf/d)": record.dcq,
      "Nominated (MMscf/d)": record.nominatedVolume,
      "Allocated (MMscf/d)": record.allocatedVolume,
      "Forecast Supply (MMscf/d)": record.forecastSupply,
      "Actual Supplied (MMscf/d)": record.actualSupplied,
      "Received (MMscf/d)": record.received,
      "Offtaken (MMscf/d)": record.offtaken,
      "Allocation Gap (MMscf/d)": record.varianceAllocation,
      "Supply Gap (MMscf/d)": record.varianceSupply,
      "Transmission Loss (MMscf/d)": record.varianceTransmission,
      "Offtake Gap (MMscf/d)": record.varianceOfftake,
      "Allocation vs DCQ (%)": record.allocationVsDcq,
      "Priority Level": record.priorityLevel,
      "Requested By": record.requestedBy,
    }),
  },

  flows: {
    templateType: "flows" as const,
    identifierFields: ["gasDay", "pipelineName"],
    requiredFields: ["Date", "Pipeline", "Flow Rate (MMscf/d)"],
    transformUploadData: (row: any, index: number) => ({
      id: `flow-upload-${Date.now()}-${index}`,
      gasDay: formatDateForCSV(row.Date || row.date),
      corridor: row.Corridor || row.corridor || "Eastern",
      pipelineName: row.Pipeline || row.pipeline,
      inletPressure: parseFloat(row["Inlet Pressure (PSI)"] || row.inletPressure || 0),
      outletPressure: parseFloat(row["Outlet Pressure (PSI)"] || row.outletPressure || 0),
      flowRate: parseFloat(row["Flow Rate (MMscf/d)"] || row.flowRate || 0),
      temperature: parseFloat(row["Temperature (°C)"] || row.temperature || 25),
      status: row.Status || row.status || "Operational",
    }),
    transformExportData: (record: any) => ({
      Date: record.gasDay,
      Pipeline: record.pipelineName,
      Corridor: record.corridor,
      "Inlet Pressure (PSI)": record.inletPressure,
      "Outlet Pressure (PSI)": record.outletPressure,
      "Flow Rate (MMscf/d)": record.flowRate,
      "Temperature (°C)": record.temperature,
      Status: record.status,
    }),
  },

  deliveries: {
    templateType: "deliveries" as const,
    identifierFields: ["gasDay", "customer"],
    requiredFields: ["Date", "Customer", "Delivered (MMscf/d)"],
    transformUploadData: (row: any, index: number) => ({
      id: `del-upload-${Date.now()}-${index}`,
      gasDay: formatDateForCSV(row.Date || row.date),
      corridor: row.Corridor || row.corridor || "Eastern",
      customer: row.Customer || row.customer,
      contractedVolume: parseFloat(row["Contracted (MMscf/d)"] || row.contracted || 0),
      deliveredVolume: parseFloat(row["Delivered (MMscf/d)"] || row.delivered || 0),
      shortfall: parseFloat(row["Shortfall (MMscf/d)"] || row.shortfall || 0),
      revenue: parseFloat(row["Revenue (₦)"] || row.revenue || 0),
      deliveryPoint: "Main Terminal",
      status: row.Status || row.status || "Delivered",
    }),
    transformExportData: (record: any) => ({
      Date: record.gasDay,
      Customer: record.customer,
      Corridor: record.corridor,
      "Contracted (MMscf/d)": record.contractedVolume,
      "Delivered (MMscf/d)": record.deliveredVolume,
      "Shortfall (MMscf/d)": record.shortfall,
      "Revenue (₦)": record.revenue,
      "Delivery Point": record.deliveryPoint,
      Status: record.status,
    }),
  },

  deferment: {
    templateType: "deferment" as const,
    identifierFields: ["gasDay", "facilityName"],
    requiredFields: ["Date", "Station/Pipeline", "Deferred (MMscf/d)"],
    transformUploadData: (row: any, index: number) => ({
      id: `def-upload-${Date.now()}-${index}`,
      gasDay: formatDateForCSV(row.Date || row.date),
      corridor: row.Corridor || row.corridor || "Eastern",
      facilityName: row["Station/Pipeline"] || row.facility || row.station,
      facilityType: "Pipeline",
      plannedProduction: parseFloat(row["Planned (MMscf/d)"] || row.planned || 0),
      actualProduction: parseFloat(row["Actual (MMscf/d)"] || row.actual || 0),
      deferredVolume: parseFloat(row["Deferred (MMscf/d)"] || row.deferred || 0),
      reason: row.Reason || row.reason || "Unknown",
      category: row.Category || row.category || "Operational",
      estimatedLoss: 0,
      status: "Open",
    }),
    transformExportData: (record: any) => ({
      Date: record.gasDay,
      "Station/Pipeline": record.facilityName,
      Corridor: record.corridor,
      Type: record.facilityType,
      "Planned (MMscf/d)": record.plannedProduction,
      "Actual (MMscf/d)": record.actualProduction,
      "Deferred (MMscf/d)": record.deferredVolume,
      Reason: record.reason,
      Category: record.category,
      "Estimated Loss (₦)": record.estimatedLoss,
      Status: record.status,
    }),
  },

  volumes: {
    templateType: "volumes" as const,
    identifierFields: ["gasDay"],
    requiredFields: ["Date", "Produced (MMscf/d)", "Delivered (MMscf/d)"],
    transformUploadData: (row: any, index: number) => ({
      id: `vol-upload-${Date.now()}-${index}`,
      gasDay: formatDateForCSV(row.Date || row.date),
      produced: parseFloat(row["Produced (MMscf/d)"] || row.produced || 0),
      nglExtracted: parseFloat(row["NGL Extracted (MMscf/d)"] || row.nglExtracted || 0),
      receivedIntoTransmission: parseFloat(row["Into Transmission (MMscf/d)"] || row.receivedIntoTransmission || 0),
      fuelGas: parseFloat(row["Fuel Gas (MMscf/d)"] || row.fuelGas || 0),
      linePackChange: parseFloat(row["Line Pack Δ (MMscf/d)"] || row.linePackChange || 0),
      delivered: parseFloat(row["Delivered (MMscf/d)"] || row.delivered || 0),
      ufg: parseFloat(row["UFG (MMscf/d)"] || row.ufg || 0),
      ufgPercent: parseFloat(row["UFG %"] || row.ufgPercent || 0),
    }),
    transformExportData: (record: any) => ({
      Date: record.gasDay,
      "Produced (MMscf/d)": record.produced,
      "NGL Extracted (MMscf/d)": record.nglExtracted,
      "Into Transmission (MMscf/d)": record.receivedIntoTransmission,
      "Fuel Gas (MMscf/d)": record.fuelGas,
      "Line Pack Δ (MMscf/d)": record.linePackChange,
      "Delivered (MMscf/d)": record.delivered,
      "UFG (MMscf/d)": record.ufg,
      "UFG %": record.ufgPercent,
    }),
  },

  incidents: {
    templateType: "incidents" as const,
    identifierFields: ["dateOccurred", "facilityName"],
    requiredFields: ["Date Occurred", "Title", "Facility", "Severity", "Category"],
    transformUploadData: (row: any, index: number) => ({
      id: `inc-upload-${Date.now()}-${index}`,
      title: row.Title || row.title,
      description: row.Description || row.description || "",
      dateOccurred: formatDateForCSV(row["Date Occurred"] || row.dateOccurred),
      dateReported: formatDateForCSV(row["Date Reported"] || row.dateReported || row["Date Occurred"]),
      facilityType: row["Facility Type"] || row.facilityType || "pipeline",
      facilityId: `facility-${index}`,
      facilityName: row.Facility || row.facility || row.facilityName,
      corridor: row.Corridor || row.corridor || "Eastern",
      category: row.Category || row.category || "equipment-failure",
      severity: row.Severity || row.severity || "medium",
      status: row.Status || row.status || "open",
      deferment: parseFloat(row["Deferment (MMscf/d)"] || row.deferment || 0),
      estimatedLoss: parseFloat(row["Estimated Loss ($)"] || row.estimatedLoss || 0),
      reportedBy: row["Reported By"] || row.reportedBy || "System Upload",
      assignedTo: row["Assigned To"] || row.assignedTo || "",
      location: {
        coordinates: [0, 0],
      },
      remarks: [],
    }),
    transformExportData: (record: any) => ({
      "Date Occurred": record.dateOccurred,
      "Date Reported": record.dateReported,
      Title: record.title,
      Description: record.description,
      Facility: record.facilityName,
      "Facility Type": record.facilityType,
      Corridor: record.corridor,
      Category: record.category,
      Severity: record.severity,
      Status: record.status,
      "Deferment (MMscf/d)": record.deferment,
      "Estimated Loss ($)": record.estimatedLoss,
      "Reported By": record.reportedBy,
      "Assigned To": record.assignedTo || "",
    }),
  },
};
