// Upload/Export configurations for each report type

import { formatDateForCSV } from "./csv-utils";

export const REPORT_CONFIGS = {
  nominations: {
    templateType: "nominations" as const,
    identifierFields: ["gasDay", "offtaker"],
    requiredFields: ["Date", "Customer", "DCQ (MMscf/d)", "Nominated (MMscf/d)"],
    transformUploadData: (row: any, index: number) => ({
      id: `nom-upload-${Date.now()}-${index}`,
      gasDay: formatDateForCSV(row.Date || row.date),
      corridor: row.Corridor || row.corridor || "Eastern",
      offtaker: row.Customer || row.customer || row.offtaker,
      dcq: parseFloat(row["DCQ (MMscf/d)"] || row.dcq || 0),
      priorityLevel: "Normal",
      requestedBy: "System Upload",
      nominatedVolume: parseFloat(row["Nominated (MMscf/d)"] || row.nominated || 0),
      allocatedVolume: parseFloat(row["Confirmed (MMscf/d)"] || row.confirmed || row["Nominated (MMscf/d)"] || 0),
      forecastSupply: parseFloat(row["Nominated (MMscf/d)"] || row.nominated || 0),
      allocationVsDcq: 0,
    }),
    transformExportData: (record: any) => ({
      Date: record.gasDay,
      Customer: record.offtaker,
      Corridor: record.corridor,
      "DCQ (MMscf/d)": record.dcq,
      "Nominated (MMscf/d)": record.nominatedVolume,
      "Allocated (MMscf/d)": record.allocatedVolume,
      "Forecast Supply (MMscf/d)": record.forecastSupply,
      "Allocation vs DCQ (%)": record.allocationVsDcq,
      "Priority Level": record.priorityLevel,
      "Requested By": record.requestedBy,
    }),
  },

  flows: {
    templateType: "flows" as const,
    identifierFields: ["gasDay", "pipelineName"],
    requiredFields: ["Date", "Pipeline", "Flow Rate (MMscf/d)"],
    transformUploadData: (row: any, index: number) => ({
      id: `flow-upload-${Date.now()}-${index}`,
      gasDay: formatDateForCSV(row.Date || row.date),
      corridor: row.Corridor || row.corridor || "Eastern",
      pipelineName: row.Pipeline || row.pipeline,
      inletPressure: parseFloat(row["Inlet Pressure (PSI)"] || row.inletPressure || 0),
      outletPressure: parseFloat(row["Outlet Pressure (PSI)"] || row.outletPressure || 0),
      flowRate: parseFloat(row["Flow Rate (MMscf/d)"] || row.flowRate || 0),
      temperature: parseFloat(row["Temperature (°C)"] || row.temperature || 25),
      status: row.Status || row.status || "Operational",
    }),
    transformExportData: (record: any) => ({
      Date: record.gasDay,
      Pipeline: record.pipelineName,
      Corridor: record.corridor,
      "Inlet Pressure (PSI)": record.inletPressure,
      "Outlet Pressure (PSI)": record.outletPressure,
      "Flow Rate (MMscf/d)": record.flowRate,
      "Temperature (°C)": record.temperature,
      Status: record.status,
    }),
  },

  deliveries: {
    templateType: "deliveries" as const,
    identifierFields: ["gasDay", "customer"],
    requiredFields: ["Date", "Customer", "Delivered (MMscf/d)"],
    transformUploadData: (row: any, index: number) => ({
      id: `del-upload-${Date.now()}-${index}`,
      gasDay: formatDateForCSV(row.Date || row.date),
      corridor: row.Corridor || row.corridor || "Eastern",
      customer: row.Customer || row.customer,
      contractedVolume: parseFloat(row["Contracted (MMscf/d)"] || row.contracted || 0),
      deliveredVolume: parseFloat(row["Delivered (MMscf/d)"] || row.delivered || 0),
      shortfall: parseFloat(row["Shortfall (MMscf/d)"] || row.shortfall || 0),
      revenue: parseFloat(row["Revenue (₦)"] || row.revenue || 0),
      deliveryPoint: "Main Terminal",
      status: row.Status || row.status || "Delivered",
    }),
    transformExportData: (record: any) => ({
      Date: record.gasDay,
      Customer: record.customer,
      Corridor: record.corridor,
      "Contracted (MMscf/d)": record.contractedVolume,
      "Delivered (MMscf/d)": record.deliveredVolume,
      "Shortfall (MMscf/d)": record.shortfall,
      "Revenue (₦)": record.revenue,
      "Delivery Point": record.deliveryPoint,
      Status: record.status,
    }),
  },

  flare: {
    templateType: "flare" as const,
    identifierFields: ["gasDay", "station"],
    requiredFields: ["Date", "Station", "Gas Flared (MMscf/d)"],
    transformUploadData: (row: any, index: number) => ({
      id: `flare-upload-${Date.now()}-${index}`,
      gasDay: formatDateForCSV(row.Date || row.date),
      corridor: row.Corridor || row.corridor || "Eastern",
      station: row.Station || row.station,
      gasProduced: parseFloat(row["Gas Produced (MMscf/d)"] || row.produced || 0),
      gasUtilized: parseFloat(row["Gas Utilized (MMscf/d)"] || row.utilized || 0),
      gasFlared: parseFloat(row["Gas Flared (MMscf/d)"] || row.flared || 0),
      flareRate: parseFloat(row["Flare Rate (%)"] || row.flareRate || 0),
      reason: row.Reason || row.reason || "Operational",
    }),
    transformExportData: (record: any) => ({
      Date: record.gasDay,
      Station: record.station,
      Corridor: record.corridor,
      "Gas Produced (MMscf/d)": record.gasProduced,
      "Gas Utilized (MMscf/d)": record.gasUtilized,
      "Gas Flared (MMscf/d)": record.gasFlared,
      "Flare Rate (%)": record.flareRate,
      Reason: record.reason,
    }),
  },

  deferment: {
    templateType: "deferment" as const,
    identifierFields: ["gasDay", "facilityName"],
    requiredFields: ["Date", "Station/Pipeline", "Deferred (MMscf/d)"],
    transformUploadData: (row: any, index: number) => ({
      id: `def-upload-${Date.now()}-${index}`,
      gasDay: formatDateForCSV(row.Date || row.date),
      corridor: row.Corridor || row.corridor || "Eastern",
      facilityName: row["Station/Pipeline"] || row.facility || row.station,
      facilityType: "Pipeline",
      plannedProduction: parseFloat(row["Planned (MMscf/d)"] || row.planned || 0),
      actualProduction: parseFloat(row["Actual (MMscf/d)"] || row.actual || 0),
      deferredVolume: parseFloat(row["Deferred (MMscf/d)"] || row.deferred || 0),
      reason: row.Reason || row.reason || "Unknown",
      category: row.Category || row.category || "Operational",
      estimatedLoss: 0,
      status: "Open",
    }),
    transformExportData: (record: any) => ({
      Date: record.gasDay,
      "Station/Pipeline": record.facilityName,
      Corridor: record.corridor,
      Type: record.facilityType,
      "Planned (MMscf/d)": record.plannedProduction,
      "Actual (MMscf/d)": record.actualProduction,
      "Deferred (MMscf/d)": record.deferredVolume,
      Reason: record.reason,
      Category: record.category,
      "Estimated Loss (₦)": record.estimatedLoss,
      Status: record.status,
    }),
  },
};
